pool:
  name: Default

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8.0'
  inputs:
    versionSpec: 3.8.0
    disableDownloadFromRegistry: true

- script: |
    conda update -n base -c defaults conda
    conda create -n myenv python=3.8 -y
    conda activate myenv
  displayName: 'Setup Conda Environment'

- script: |
    conda install -y numpy=1.21 pandas=1.3 matplotlib=3.4 scikit-learn=1.0 lightgbm=3.3 pytest=7.0 black flake8
  displayName: 'Install Dependencies with Conda'

- script: |
    conda list
  displayName: 'Verify Installed Dependencies'

- script: |
    conda activate myenv
    python -c "import numpy; import pandas; import matplotlib; import sklearn; import lightgbm; print('All imports successful')"
  displayName: 'Test Installed Libraries'
