[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = ">=1.21.0"  # Updated to meet pandas requirements
pandas = "1.3.5"
scikit-learn = "1.0.2"
lightgbm = "3.3.5"
joblib = "1.1.1"
matplotlib = "3.5.1"
pytest = "7.2.2"

[tool.poetry.group.azure.dependencies]
azure-ai-ml = "1.15.0"
azure-identity = "1.12.0"
azure-storage-blob = "12.13.0"
inference-schema = "1.5.1"
azureml-core = "1.48.0"
azureml-mlflow = "1.48.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
azure = ["azure-ai-ml", "azure-identity", "azure-storage-blob", "inference-schema", "azureml-core", "azureml-mlflow"]
