[tool.poetry]
name = "classification"
version = "0.1.0"
description = "classification"
authors = ["Deep Knowledge <Deepp.Knowledge@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"  # First version fully supporting Python 3.9
pandas = "*"  # Compatible with Python 3.9
scikit-learn = "*"  # Compatible with Python 3.9
lightgbm = "*"  # Compatible with Python 3.9
joblib = "*"  # Compatible with Python 3.9
matplotlib = "*"  # Updated version for Python 3.9
pytest = "*"  # Compatible with Python 3.9
inference-schema ="*"

[tool.poetry.group.azure.dependencies]
azure-ai-ml = "*"  # Compatible with Python 3.9
azure-identity = "*"  # Compatible with Python 3.9
azure-storage-blob = "*"  # Compatible with Python 3.9
azureml-core = "*"  # Compatible with Python 3.9
azureml-mlflow = "*"  # Compatible with Python 3.9


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
azure = ["azure-ai-ml", "azure-identity", "azure-storage-blob", "inference-schema", "azureml-core", "azureml-mlflow"]