[tool.poetry]
name = "classification-demo"
version = "0.1.0"
description = "A comprehensive machine learning classification demonstration"
authors = ["Deep Knowledge <Deepp.Knowledge@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.0"
pandas = "^1.4.0"
matplotlib = "^3.5.0"
scikit-learn = "^1.0.0"
seaborn = "^0.11.0"
jupyterlab = "^3.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.0"
mypy = "^0.950"
black = "^22.3.0"
isort = "^5.10.0"

[tool.poetry.scripts]
classification-demo = "classification_demo.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true

[tool.black]
line-length = 88
target-version = ['py39']