[tool.poetry]
name = "breast-cancer-classification"
version = "0.1.0"
description = "A machine learning project for breast cancer classification"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"
pandas = "^1.3.0"
matplotlib = "^3.4.0"
scikit-learn = "^1.0.0"
lightgbm = "^3.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^22.3.0"
flake8 = "^4.0.0"
#scipy ="1.9.3"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"