[tool.poetry]
name = "classification"
version = "0.1.0"
description = "classification"
authors = ["Deep Knowledge <Deepp.Knowledge@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "1.20.3"  # First version fully supporting Python 3.9
pandas = "1.3.5"  # Compatible with Python 3.9
scikit-learn = "1.0.2"  # Compatible with Python 3.9
lightgbm = "3.3.5"  # Compatible with Python 3.9
joblib = "1.1.1"  # Compatible with Python 3.9
matplotlib = "3.5.1"  # Updated version for Python 3.9
pytest = "7.2.2"  # Compatible with Python 3.9
inference-schema = {version = "1.5.1", markers = "python_version >= '3.9' and python_version < '3.11'"}

[tool.poetry.group.azure.dependencies]
azure-ai-ml = "1.15.0"  # Compatible with Python 3.9
azure-identity = "1.12.0"  # Compatible with Python 3.9
azure-storage-blob = "12.13.0"  # Compatible with Python 3.9
azureml-core = "1.48.0"  # Compatible with Python 3.9
azureml-mlflow = "1.48.0"  # Compatible with Python 3.9


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
azure = ["azure-ai-ml", "azure-identity", "azure-storage-blob", "inference-schema", "azureml-core", "azureml-mlflow"]