[tool.poetry]
name = "classification-demo"
version = "0.1.0"
description = "A Python project demonstrating classification with LightGBM and sklearn."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
python = "^3.12.0"

[tool.poetry.dependencies]
python = "^3.12.0"
numpy = "^1.23.0"
pandas = "^1.5.0"
matplotlib = "^3.7.0"
scikit-learn = "^1.1.0"
lightgbm = "^3.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
