[tool.poetry]
name = "classification"
version = "0.1.0"
description = "A project for classification tasks"
authors = ["Deep Knowledge <Deepp.Knowledge@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9"
numpy = "1.21.0"
pandas = "1.3.5"
scikit-learn = "1.0.2"
lightgbm = "3.3.5"
joblib = "1.1.1"
matplotlib = "3.5.1"
pytest = "7.2.2"
scipy="1.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"