name: classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas=1.3.5
  - joblib
  - matplotlib=3.8.3
  - lightgbm
  - pytest=8.3.4
  - black=24.2.0
  - flake8=7.0.0
  - pre-commit>=4.0.1
  - azure-ai-ml>=1.23.0
  - azure-identity>=1.19.0
  - azure-mgmt-resource>=23.2.0
  - azure-storage-blob>=12.24.0
  - azure-mgmt-storage>=21.2.1
  - pip
  - pip:
      - azure-ai-ml>=1.23.0
      - azure-identity>=1.19.0
      - azure-storage-blob>=12.24.0
      - inference-schema
      - azureml-core
      - azureml-mlflow
