channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=21.3.1
- pytest
- pytest-cov
- matplotlib>=3.7.0
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - distributed==2021.10.0
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - lightgbm==3.3.5
  - more-itertools==10.3.0
  - pandas==1.5.3
  - scikit-learn==1.5.2
  - zstandard==0.23.0
name: mlflow-env



