[tool.poetry]
name = "mlflow-env"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.11.0"
requests = "^2.25.0"
pytest = "7.4.0"
pytest-cov = "4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"