$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: fruit-endpoint
model: azureml:Fruit_FINAL_model:6
code_configuration:
  code: .
  scoring_script: score.py
environment: azureml://registries/azureml/environments/lightgbm-3.3/versions/53
instance_type: Standard_F4s_v2
instance_count: 1
app_insights_enabled: true